Include bcutil-jdk18on.jar into the dependencies.
When use Instance Principal Auth to run functional test(nosql-drvier 5.4.15),
got java.lang.NoClassDefFoundError: org/bouncycastle/asn1/oiw/OIWObjectIdentifiers
error, and the nosql-drvier 5.4.15 uses bouncycastle 1.78.

Bouncycastle has changed the packaging since 1.78, the org/bouncycastle/asn1/*.class are
moved to bcutil-jdk18on.jar, so need include bcutil-jdk18on.jar into the dependencies
of nosql driver.

In driver/pom.xml, all the dependencies of bcprov-jdk18on and bcpkix-jdk18on are
explicitly excluded, and the bcutil-jdk18on is dependency for test scope only.
The bcutil-jdk18on and bcprov-jdk18on are only dependencies of bcpkix-jdk18on, and
no dependency for bcprov-jdk18on.

So to fix it, simply remove the dependency exclusions of bcpkix-jdk18on and bcprov-jdk18on,
and also remove dependency of bcutil-jdk18on for test, then the bcutil-jdk18on will be
included into dependencies.